[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
name = "shdw-node-stats"
version = "0.1.0"
author = "AnyNodes"
author_email = "anynodes@outlook.com"
description = "A tool to fetch and record ShadowDrive node statistics from an API and save them to a CSV file."
long_description = "file: README.md"
long_description_content_type = "text/markdown"
url = "https://github.com/AnyNodes/shdw-node-stats"
project_urls = {
    "Bug Tracker": "https://github.com/AnyNodes/shdw-node-stats/issues"
}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
packages = ["."]
install_requires = ["requests>=2.25.1"]
scripts = ["NodeStats.py"]

[tool.setuptools.dynamic]
requires-python = ">=3.6"
